### ISSUE TITLE
Ansible bootstrap playbook requires whois package to be installed

### ISSUE THREAD

**Issue by erhudy** [bloomberg/chef-bcpc#1012]
I introduced a dependency on the `whois` package that isn't installed on Ubuntu by default when I added the emergency break-glass password that is generated with the `mkpasswd` command (which comes from the `whois` package).

**Comment by kelvk** [comment]
If you are building an Internet-disconnected bootstrap, this will fail because the installation media is likely not mounted. Per @erhudy, at least it reminds the operator that this package is essential before proceeding. The appropriate action to avoid this condition is to select `whois` package during installation per https://github.com/bloomberg/chef-bcpc/blob/master/docs/ansible_local_build_guide.md.

**Comment by kelvk** [comment]
Meant to write in the PR...
