### ISSUE TITLE
Pin version of ubuntu mini.iso

### ISSUE THREAD

**Issue by kelvk** [bloomberg/chef-bcpc#1067]
Bootstrapping nodes with version-frozen apt mirror can fail when the kernel version in [mini.iso](https://github.com/bloomberg/chef-bcpc/blob/master/bootstrap/shared/shared_prereqs.sh#L97) is newer than the apt mirror's. Perhaps we should pin the version of mini.iso that we download.

**Comment by erhudy** [comment]
This is strange to me, because I had never been able to find an updated version of the mini ISO. It did not seem like Canonical re-spun the mini ISO with each point release when I was doing some work that required fixes that had been implemented in 14.04.4 only.

**Comment by kamidzi** [comment]
Related to #992 ?

**Comment by erhudy** [comment]
I don't think so. I think @kelvk reported this issue originally because when 14.04.5 was released, Canonical did do some updated mini ISOs that originally interfered with us because our frozen mirror was slightly older than what the mini ISO was expecting, and so package installations would blow up during preseed. Since that time we have updated the frozen mirror to 14.04.5+ and the most current mini ISO works again.
