### ISSUE TITLE
Rabbit doesn't deal with partitions

### ISSUE THREAD

**Issue by caiush** [bloomberg/chef-bcpc#406]
I've seen partitions in rabbit when you inter-rack problems Look at the docs here:
https://www.rabbitmq.com/partitions.html
I think we probably want to set:
```
cluster_partition_handling: pause_minority 
```
in the rabbit configuration. We might want to even try out the auto heal functionality (see above docs). Both need some testing however.

**Comment by kelvk** [comment]
I tested `pause_minority` with seemingly good effect. It works as expected and a recovered node can rejoin the cluster without manual intervention (we currently have to restart rabbitmq). The concern highlighted may also be mitigated with recent versions of RabbitMQ where connections are killed more immediately, as mentioned by Simon MacMullen in the page's comments, and reduction of RabbitMQ heartbeat (currently 580 seconds!) to quickly detect failed nodes.

@erhudy also opined that loss of messages is probably OK (if I understand him right) since use of AMQP here is merely for RPC.

I intend to run the Jepsen test against a recent RabbitMQ version, but I have not been able to build the test suite in my environment thus far.

**Comment by kelvk** [comment]
Implemented by #930
