### ISSUE TITLE
cluster-vip.sh broken by multiple VIPs now on chef-bcpc

### ISSUE THREAD

**Issue by mihalis68** [bloomberg/chef-bcpc#488]
cluster-vip.sh was implemented to allow quick diagnosis of which cluster member currently holds the VIP. We now have 2 or 3 VIPs in our clusters and the tool currently doesn't work.

**Comment by kkoh61** [comment]
Due to the order of defined VIP parameters in our environments file, the management VIP is always searched upon despite the presence of additional VIPs (floating, and most recently, monitoring). However, I have observed that cluster.txt could be pre-populated with upper-case MAC addresses, thereby causing the tool to not return the VIP holder. Making grep in https://github.com/bloomberg/chef-bcpc/blob/master/cluster-vip.sh#L28 case-insensitive should at least unbreak it in the short-term, though extending the tool to accommodate multiple VIPs will be handy. I think if we are to rewrite the tool, we may want to consider using chef/knife for MAC address search.

**Comment by mihalis68** [comment]
Actually yes I came across this myself and put the -i on but forgot to check that in. More troublingly, however, I find it no longer works with multiple-vip systems - doesn't even give me the management vip. Will take a look at fixing this asap.
