### ISSUE TITLE
Incorrect number of connections in mysql config file

### ISSUE THREAD

**Issue by caiush** [bloomberg/chef-bcpc#525]
I think this was a regression. The `max_connections` in the `mysql-head.rb` recipe is set too low and should be 2x of the current value. 

Compare the new mysql-head recipe:
https://github.com/bloomberg/chef-bcpc/blob/master/cookbooks/bcpc/recipes/mysql-head.rb#L64

with the old mysql.rb recipe
https://github.com/bloomberg/chef-bcpc/blob/master/cookbooks/bcpc/recipes/mysql.rb#L88

**Comment by kamidzi** [comment]
Out of curiosity, from where are these scaling factors derived: 110 connections/head node && 10 per all others?

**Comment by kkoh61** [comment]
@pchandra could provide more insight on the calculation, but it seems like a straight doubling to provide additional headroom since we've seen to-be-timed-out connections (another issue to look into) on MySQL exhausting max_connections around the time of VIP jumps.

I am parameterizing max_connections as well in the PR for some operational flexibility.

**Comment by pchandra** [comment]
Yeah, the scaling factors were derived empirically (back in the grizzly days) since I saw ~25 conns from a head and 2 from each worknode, so I made them 50 & 5 to allow for headroom. The later doubling again (to 100 & 10) was due to the storm of reconnects that happens when the VIP jumps (which was exacerbated by various nova processes doing silly things like defaulting to launching a number of instances equal to the number of procs in the machines). Should be totally safe to leave it at the higher 100/10 factors since this is a control-plane only DB.
