### ISSUE TITLE
Consider disabling durable queues

### ISSUE THREAD

**Issue by jerenkrantz** [bloomberg/chef-bcpc#574]
With Trusty+Kilo, I saw `nova-conductor` get really confused - with log messages like:

```
2015-05-17 10:21:50.980 9487 INFO oslo_messaging._drivers.impl_rabbit [req-55994053-c547-42a2-97de-35c411c4588e - - - - -] The exchange to reply to reply_73816cf9731c45afa2a7c5fcd57865e6 doesn't exist yet, retrying...
```

I _believe_ that this is related to the fact that some of the RabbitMQ exchanges are per-process - so, when everything is restarted (e.g. cold start), `nova-conductor` still wants those named exchanges to exist and won't process other messages until they are present.  As the exchange names were only for the duration of the process, that particular named exchange will never get created - so `nova-conductor` essentially sits in a deadlock waiting for it.

Ungood.

(I'm wondering if `nova-conductor` is iterating all the queues or exchanges somehow.  I couldn't figure out how `nova-conductor` knew to look for these exchanges.)

We should chat with folks this week in Vancouver, but `nova-conductor` was way happier with handling service restarts when durability was turned off.  It could successfully come back from a cold start in my testing with durability disabled.

**Comment by erhudy** [comment]
That's a bit strange that it's occurring still. Where I found this problem during testing was not with durable queues; rather the problem occurred for me before I ever turned durable on. What it eventually ended up being caused by was problems with memcached which caused Keystone and Nova to be very slow to respond to API calls, and the issues with `nova-conductor` (among others) went away quite conclusively when the memcached problems were fixed.

However, since I misunderstood the point of Rabbit as being for RPC rather than traditional messaging, I support disabling durable again, and so I will make a PR for the change shortly.

**Comment by jerenkrantz** [comment]
It'd likely be useful to test this and see if we can reproduce after a cold start - e.g., after installation of the cluster, shut all machines off, and then restart them all.

**Comment by jerenkrantz** [comment]
As we keep changing this, it's likely good to just make this a tunable/overridable option.

**Comment by erhudy** [comment]
Filed #577 to address this.

**Comment by napomokoetle** [comment]
https://bugs.launchpad.net/oslo.messaging/+bug/1433956

I had the same error when I upgraded to Kilo tonight. The error disappeared after I set the following parameter in /etc/neutron/neutron.conf in my Openstack nodes and restarted rabbitmq and neutron processes.

[oslo_messaging_rabbit]
rabbit_durable_queues = true
