### ISSUE TITLE
update-ca-certificates needs to be run after adding SSL cert

### ISSUE THREAD

**Issue by jnegron11** [bloomberg/chef-bcpc#662]
After adding SSL certificates ( via BOOTSTRAP_ADDITIONAL_CACERTS_DIR ), update-ca-certificates is not run.

**Comment by erhudy** [comment]
I don't understand this issue. If you have added more certificates after already starting up a cluster, you will need to run `vagrant provision` to rerun the provisioners.

**Comment by erhudy** [comment]
There is also a lack of sanity checking on this provisioner at the moment that I need to add. Because of how `update-ca-certificates` works when checking for random certificates to collect, they must end in `.crt` (the provisioner does not explicitly whitelist each individual certificate, it just drops them in `/usr/local/share/ca-certificates` or whatever that path is).

**Comment by jnegron11** [comment]
I mean when creating a new cluster.  I explain:
- I created a bootstrap_config.sh and added proxy variables and an SSL directory where a custom CA root cert is ( mycert.crt ).
- I see that in the Vagrantfile (under bootstrap/vagrant_scripts/ ) there is a section that install said custom/additional SSL cert into /usr/local/share/ca-certificates but, after adding the cert, it doesn't run update-ca-certificates thus the system doesn't know that there is a new cert added.
