### ISSUE TITLE
setup_chef_cookbooks.sh has hardcoded bootstrap node hostname

### ISSUE THREAD

**Issue by mihalis68** [bloomberg/chef-bcpc#804]
```
# TODO: extract chef organization
gen_knife_config(){
  cat <<EOF
current_dir = File.dirname(__FILE__)
log_level                :info
log_location             STDOUT
node_name                "admin"
client_key               "#{current_dir}/admin.pem"
validation_client_name   "bcpc-validator"
validation_key           "#{current_dir}/bcpc-validator.pem"
chef_server_url          "https://bcpc-bootstrap/organizations/bcpc"
cache_type               'BasicFile'
cache_options( :path => "#{ENV['HOME']}/.chef/checksums" )
cookbook_path            ["#{current_dir}/../cookbooks"]
EOF
}
```

See the line "chef_server_url          "https://bcpc-bootstrap/organizations/bcpc""
this hardcodes the hostname of the bootstrap node to "bcpc-bootstrap" here. That is incorrect. We have no dependency on a fixed hostname for any member of a BCPC cluster.

**Comment by erhudy** [comment]
This was something I carried over from the previous Vagrant/PXE boot hybrid. An `/etc/hosts` entry for **bcpc-bootstrap** is inserted into all nodes bootstrapped from Cobbler (see https://github.com/bloomberg/chef-bcpc/blob/master/cookbooks/bcpc/templates/default/cobbler.bcpc_ubuntu_host.preseed.erb#L110). Using a hostname is mandatory when initiating the Chef run so that the SSL certificates retrieved via `knife ssl fetch` will work. It's not supposed to be a _hostname_, per se, but rather a way by which any given node can always find the bootstrap node. Additionally, this is needed for local builds where there is no DNS infrastructure and hostfile entries are required; an IP simply would not work for Chef for the SSL reason given previously.

**Comment by erhudy** [comment]
If you want to solve this for local builds by parameterizing this value in an environment variable, that's fine, though we'll also need to duplicate that parameter in the Chef environment so that it can be inserted into the Cobbler template appropriately.

**Comment by erhudy** [comment]
(Either that or come up with some sort of elaborate system for extracting Chef environment variables into a format usable by the bootstrap shell scripts.)
