### ISSUE TITLE
Updating certain variables in environment file does not update data bag counterpart

### ISSUE THREAD

**Issue by kamidzi** [bloomberg/chef-bcpc#927]
An example is `keystone-admin-password`. The value in the databag is sticky because of the way make_config works, whereas the source of the attribute (in the enviroment) is mutable, possibly leading to some confusion. This is likely the case with other data bag items initializing from the environment.

**Comment by kamidzi** [comment]
In the case of `keystone-admin-password`, an immediate workaround is to simply delete the entry in the databag after changing the environmental value

**Comment by erhudy** [comment]
This is known behavior. I added a **force** flag to **make_config** to force it to clobber the databag value, which is used in a few places with Ceph keys (e.g., https://github.com/bloomberg/chef-bcpc/blob/master/cookbooks/bcpc/recipes/ceph-head.rb#L277). This happens to work for Ceph because it persists the keys onto the filesystem and the databag is used as a cache rather than the authoritative source. We can't turn it on everywhere because then anything for which the databag item is the authoritative source would get blown up on every Chef run.

**Comment by kamidzi** [comment]
I understand the issue, though I'm undecided as to what would make the situation more clear: on the one hand, it can be dangerous, but then we would probably have to finely detail what can be changed how and where. I'm not even sure the ldap bind password and keystone password need to be the same? (Didn't verify)

**Comment by kamidzi** [comment]
Also, not strictly related, but I don't know where else to call people's attention to this: https://bugs.launchpad.net/glance/+bug/1467719. Triggered that while troubleshooting this databag issue.
