### ISSUE TITLE
Unable to create VMs when a head node is unreachable

### ISSUE THREAD

**Issue by kelvk** [bloomberg/chef-bcpc#928]
I have tested reproduction of this on virtual and physical nodes and seems fairly consistent.

1. Down the management interface on a non-VIP holding head node
<pre>ifdown em1</pre>
2. Test instance booting on another head node
<pre>check nova</pre> or <pre>nova --debug boot --flavor m1.tiny --image 'Cirros 0.3.4 x86_64 test1</pre>

The instance will hang in scheduling/building state.

**Comment by erhudy** [comment]
I was able to reproduce. This appears to be at least partially due to https://github.com/rabbitmq/rabbitmq-server/issues/224 (found by @kelvk, I'm just linking it), and partially possibly due to a very long heartbeat interval (580 seconds prior to 3.5.5, we are running 3.5.4 everywhere).

**Comment by erhudy** [comment]
As part of reproducing the issue, I examined stuck processes on the node that was leading on a particular queue (**conductor** in this case) and found that there are indeed wedged Erlang processes. The RabbitMQ server reports connections associated with these processes as being an **Unknown** connection, rather than the expected notation of of source and destination nodes/ports.

**Comment by erhudy** [comment]
Upgrading to 3.5.6 helped with the stuck processes issue in RabbitMQ. Modifying sysctl variables and setting `net.ipv4.tcp_retries2` to 8 instead of the default of 15 helped with evicting dead clients from RabbitMQ much faster, allowing queues like **conductor** to return to normal. Unfortunately, Galera decided enough was enough and blew up in my face, bringing testing to an abrupt end, but we can probably get significant improvement in this regard by knocking TCP retries down and upgrading RabbitMQ.

**Comment by kelvk** [comment]
Fixed
